version: "3.9"

services:
  app:
    build: ./
    container_name: kotlin-first-app
    volumes:
      - ./:/ktor-sample
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - ktor-network
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ktor
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=secret
    ports:
    - 5432:5432
    expose:
      - 5432
    networks:
      - ktor-network

networks:
  ktor-network:
    driver: bridge